version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
        - 27017:27017
        volumes:
        - data:/data
        environment:
          - MONGO_INITDB_ROOT_USERNAME=rootuser
          - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
          - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
          - ME_CONFIG_MONGODB_SERVER=mongodb

    cache:
      image: redis:6.2-alpine
      container_name: redis-cache
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass redispass
      volumes:
        - cache:/data

volumes:
  data: {}
  cache:
    driver: local

networks:
  default:
    name: mongodb_redis_network

